#!/usr/bin/env bash

if [ -z ${1+x} ]
then
  echo "Please provide an exercise name to continue"
  exit
fi

# file="exercises/$1"
file=$1

if [[ ! -f $file ]]
then
  echo "Exercise '$1' was not found"
  exit
fi

# Ensure the contracts are built
cargo creusot -- --features=contracts

contracts_location=$(ls -t target/debug/deps/libcreusot_contracts-*.rmeta | head -1)
output_file="$(basename $file .rs).mlcfg"
base="$(pwd)"

cd "$(dirname $file)"

rustup run $(rustup show active-toolchain | cut -d " "  -f 1) creusot-rustc --output-file=$output_file -- -Zno-codegen \
  --extern creusot_contracts=$base/$contracts_location \
  -Ldependency=$base/target/debug/deps/ \
  --crate-type=lib \
  "$(basename $file)"
